# Flink 공식 이미지 기반 (Java 17)
FROM flink:1.20-java17

# 작업 디렉토리 설정
WORKDIR /opt/flink

# 필수 라이브러리 JAR 복사
COPY docker/libs/flink-connector-jdbc-*.jar /opt/flink/lib/
COPY docker/libs/clickhouse-jdbc-0.6.3-all.jar /opt/flink/lib/
COPY docker/libs/flink-connector-kafka-*.jar /opt/flink/lib/
COPY docker/libs/flink-json-*.jar /opt/flink/lib/

# Flink Job JAR는 별도 폴더에 복사
RUN mkdir -p /opt/flink/usrlib
COPY ./flink-kafka-clickhouse/target/flink-kafka-clickhouse-1.0-SNAPSHOT.jar /opt/flink/usrlib/





